### ISSUE TITLE
Wrong mod uploaded to SpaceDock

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/IntegratedStackDecouplers#2]
@linuxgurugamer  The latest download on SpaceDock is for ImprovedChaseCamera instead of this mod:

- https://spacedock.info/mod/1538/Integrated%20Stack%20Decouplers

![image](https://user-images.githubusercontent.com/1559108/127419175-97f9e510-618b-495b-82fb-fd6d3b59256a.png)

**Comment by linuxgurugamer** [comment]
Fixed, thanks
